language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - pypy
  - pypy3.3-5.5-alpha

before_install:
  - sudo chmod 0777 /var/run

install:
  - pip install "nose>=1.3.0" "flake8>=2.1"
  - pip install -e .

script:
  - flake8 --show-source --ignore=E501,W391 .
  - nosetests -v
